Abstract config and implement starship prompt

diff --git a/private_dot_config/zshrc/10-aliases b/private_dot_config/zshrc/10-aliases
--- a/private_dot_config/zshrc/10-aliases
+++ b/private_dot_config/zshrc/10-aliases
@@ -18,6 +18,7 @@ alias vim='$EDITOR'
 alias ts='~/.config/ml4w/scripts/snapshot.sh'
 alias wifi='nmtui'
 alias cleanup='~/.config/ml4w/scripts/cleanup.sh'
+alias yup='rate-mirrors arch | sudo tee /etc/pacman.d/mirrorlist && yay'
 
 # -----------------------------------------------------
 # ML4W Apps
@@ -76,7 +77,7 @@ wd() {
 alias b64='base64 "`ls -tr1 | tail -n1`"'
 alias gg='lazygit'
 alias n.='nvim .'
-alias n='nvim'
+alias n=$EDITOR
 alias noise='play -n synth brownnoise brownnoise pinknoise pinknoise whitenoise whitenoise vol 0.3'
 alias nrd='npm run dev'
 alias pbcopy='xclip -sel clip'
@@ -88,7 +89,6 @@ alias sb='npx supabase'
 alias sudoedit='sudo -E -s '
 alias tmuxa='tmux attach -t '
 alias tmuxs='tmux new-session -s '
-alias vim='nvim'
 alias zr='source ~/.zshrc'
 alias cm='chezmoi'
 alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
@@ -97,3 +97,16 @@ ch() {
   curl cheat.sh/$1
 }
 
+t() {
+  wd $1
+  # Check if the session exists, discarding output
+# We can check $? for the exit status (zero for success, non-zero for failure)
+tmux has-session -t $1 2>/dev/null
+
+if [ $? != 0 ]; then
+  tmux new-session -s $1
+fi
+
+# Attach to created session
+tmux attach-session -t $1
+}
